# Generated by Django 4.1 on 2022-08-22 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('so_dien_thoai', models.CharField(max_length=15, unique=True, verbose_name='Số điện thoại')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'TaiKhoan',
            },
        ),
        migrations.CreateModel(
            name='LoaiSanPham',
            fields=[
                ('ma_loai_san_pham', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Mã loại sản phẩm')),
                ('ten_loai_san_pham', models.CharField(max_length=255, verbose_name='Tên loại sản phẩm')),
                ('mo_ta', models.TextField(help_text='Mô tả của loại sản phẩm', verbose_name='Mô tả loại sản phẩm')),
                ('ghi_chu', models.TextField(help_text='Ghi chú nội bộ', verbose_name='Ghi chú')),
            ],
            options={
                'db_table': 'LoaiSanPham',
            },
        ),
        migrations.CreateModel(
            name='NhaCungCap',
            fields=[
                ('ma_ncc', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Mã nhà cung cấp')),
                ('ten_ncc', models.CharField(max_length=100, verbose_name='Tên nhà cung cấp')),
                ('so_dien_thoai', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('email', models.CharField(max_length=50, verbose_name='Địa chỉ email')),
                ('ma_so_thue', models.CharField(max_length=20, verbose_name='Địa chỉMã số thuế')),
                ('dia_chi', models.CharField(max_length=255, verbose_name='Địa chỉ')),
                ('ghi_chu', models.TextField(help_text='Ghi chú nội bộ', verbose_name='Ghi chú')),
            ],
            options={
                'db_table': 'NhaCungCap',
            },
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('ma_nhan_vien', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Tên nhân viên')),
                ('ten_nhan_vien', models.CharField(max_length=30, verbose_name='Tên nhân viên')),
                ('so_dien_thoai', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('so_cccd', models.CharField(max_length=15, verbose_name='Số căn cước công dân')),
                ('dia_chi', models.CharField(max_length=255, verbose_name='Địa chỉ')),
                ('ngay_sinh', models.DateField(default='1900-01-01', verbose_name='Ngày sinh')),
                ('email', models.CharField(max_length=50, verbose_name='Địa chỉ email')),
                ('trang_thai', models.BooleanField(verbose_name='Trạng thái')),
            ],
            options={
                'db_table': 'NhanVien',
            },
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('ma_san_pham', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Mã sản phẩm')),
                ('ten_san_pham', models.CharField(max_length=255, verbose_name='Tên sản phẩm')),
                ('mo_ta', models.TextField(verbose_name='Mô tả sản phẩm')),
                ('hinh_anh', models.CharField(blank=True, max_length=255, verbose_name='Hình ảnh sản phẩm')),
                ('so_luong', models.PositiveIntegerField(verbose_name='Số lượng')),
                ('ma_vach', models.CharField(max_length=15, verbose_name='Mã vạch')),
                ('anh_ma_vach', models.CharField(max_length=255, verbose_name='Ảnh mã vạch')),
                ('loai_san_pham', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ds_san_pham', to='management.loaisanpham')),
                ('nha_cung_cap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ds_san_pham', to='management.nhacungcap')),
            ],
            options={
                'db_table': 'SanPham',
            },
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('ma_khach_hang', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Mã khách hàng')),
                ('ten_khach_hang', models.CharField(max_length=30, verbose_name='Tên khách hàng')),
                ('ghi_chu', models.TextField(blank=True, verbose_name='Tên khách hàng')),
                ('nguoi_dung', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'KhachHang',
            },
        ),
        migrations.CreateModel(
            name='DonViTinh',
            fields=[
                ('ma_don_vi', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã đơn vị tính')),
                ('don_vi', models.CharField(max_length=30, verbose_name='Tên đơn vị tính')),
                ('gia_tri_quy_doi', models.PositiveIntegerField(help_text='Đơn vị này bằng bao nhiêu đơn vị mặc định?', verbose_name='Giá trị quy đổi')),
                ('don_vi_mac_dinh_ban_hang', models.BooleanField(help_text='Là đơn vị mặc định để bán hàng hay không?', verbose_name='Đơn vị mặc định bán hàng')),
                ('don_vi_mac_dinh', models.BooleanField(help_text='Là đơn vị mặc định hay không (thường là đơn vị nhỏ nhất)', verbose_name='Đơn vị mặc định')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_don_vi_tinh', to='management.sanpham')),
            ],
            options={
                'db_table': 'DonViTinh',
            },
        ),
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('ma_don_hang', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Mã đơn hàng')),
                ('ghi_chu', models.TextField(verbose_name='Ghi chú')),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.khachhang')),
            ],
            options={
                'db_table': 'DonHang',
            },
        ),
        migrations.CreateModel(
            name='BienThe',
            fields=[
                ('ma_bien_the', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã biến thể')),
                ('ten_bien_the', models.CharField(max_length=30, verbose_name='Tên biến thể')),
                ('ma_vach', models.CharField(max_length=15, verbose_name='Mã vạch')),
                ('anh_ma_vach', models.CharField(max_length=255, verbose_name='Ảnh mã vạch')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_bien_the', to='management.sanpham')),
            ],
            options={
                'db_table': 'BienThe',
            },
        ),
        migrations.CreateModel(
            name='BangGia',
            fields=[
                ('ma_bang_gia', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã bảng giá')),
                ('gia', models.FloatField(verbose_name='Giá bán')),
                ('bat_dau', models.DateTimeField(help_text='Thời gian bắt đâu áp dụng bảng giá', verbose_name='Thời gian bắt đầu')),
                ('ket_thuc', models.DateTimeField(help_text='Thời gian kết thúc áp dụng bảng giá', verbose_name='Thời gian kết thúc')),
                ('bien_the', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_bang_gia', to='management.bienthe', verbose_name='Biến thể')),
                ('don_vi_tinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_bang_gia', to='management.donvitinh', verbose_name='Đơn vị tính')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_bang_gia', to='management.sanpham', verbose_name='Sản phẩm')),
            ],
        ),
    ]
