# Generated by Django 4.0.7 on 2022-08-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nhacungcap',
            old_name='so_dien_thoai',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='nhanvien',
            old_name='so_dien_thoai',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='so_dien_thoai',
            new_name='phone',
        ),
    ]
