# Generated by Django 4.0.7 on 2022-08-25 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_rename_so_dien_thoai_nhacungcap_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Mã khách hàng')),
                ('fullname', models.CharField(max_length=30, verbose_name='Tên khách hàng')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Mã đơn hàng')),
                ('note', models.TextField(verbose_name='Ghi chú')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='management.customer')),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('price_list_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã bảng giá')),
                ('price', models.FloatField(verbose_name='Giá bán')),
                ('start_date', models.DateTimeField(help_text='Thời gian bắt đâu áp dụng bảng giá', verbose_name='Thời gian bắt đầu')),
                ('end_date', models.DateTimeField(help_text='Thời gian kết thúc áp dụng bảng giá', verbose_name='Thời gian kết thúc')),
            ],
            options={
                'db_table': 'PriceList',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Mã sản phẩm')),
                ('product_name', models.CharField(max_length=255, verbose_name='Tên sản phẩm')),
                ('description', models.TextField(verbose_name='Mô tả sản phẩm')),
                ('image', models.CharField(blank=True, max_length=255, verbose_name='Hình ảnh sản phẩm')),
                ('barcode', models.CharField(max_length=15, verbose_name='Mã vạch')),
                ('barcode_image', models.CharField(max_length=255, verbose_name='Ảnh mã vạch')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('product_type_id', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Mã loại sản phẩm')),
                ('product_type_name', models.CharField(max_length=255, verbose_name='Tên loại sản phẩm')),
                ('description', models.TextField(help_text='Mô tả của loại sản phẩm', verbose_name='Mô tả loại sản phẩm')),
                ('note', models.TextField(help_text='Ghi chú nội bộ', verbose_name='Ghi chú')),
            ],
            options={
                'db_table': 'ProductType',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Mã nhân viên')),
                ('fullname', models.CharField(max_length=30, verbose_name='Tên nhân viên')),
                ('phone', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('cccd', models.CharField(max_length=15, verbose_name='Số căn cước công dân')),
                ('address', models.CharField(max_length=255, verbose_name='Địa chỉ')),
                ('day_of_birth', models.DateField(default='1900-01-01', verbose_name='Ngày sinh')),
                ('email', models.CharField(max_length=50, verbose_name='Địa chỉ email')),
                ('status', models.BooleanField(verbose_name='Trạng thái')),
            ],
            options={
                'db_table': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Mã nhà cung cấp')),
                ('supplier_name', models.CharField(max_length=100, verbose_name='Tên nhà cung cấp')),
                ('phone', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('email', models.CharField(max_length=50, verbose_name='Địa chỉ email')),
                ('address', models.CharField(max_length=255, verbose_name='Địa chỉ')),
                ('note', models.TextField(help_text='Ghi chú nội bộ', verbose_name='Ghi chú')),
            ],
            options={
                'db_table': 'Supplier',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã đơn vị tính')),
                ('unit_name', models.CharField(max_length=30, verbose_name='Tên đơn vị tính')),
                ('value', models.PositiveIntegerField(help_text='Đơn vị này bằng bao nhiêu đơn vị mặc định?', verbose_name='Giá trị quy đổi')),
                ('allow_sale', models.BooleanField(help_text='Cho phép bán hàng bằng đơn vị này không?', verbose_name='Đơn vị được phép bán hàng')),
                ('is_base_unit', models.BooleanField(help_text='Có phải là đơn vị cơ bản hay không (đơn vị nhỏ nhất)', verbose_name='Đơn vị cơ bản')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='management.product')),
            ],
            options={
                'db_table': 'Unit',
            },
        ),
        migrations.RemoveField(
            model_name='banggia',
            name='bien_the',
        ),
        migrations.RemoveField(
            model_name='banggia',
            name='don_vi_tinh',
        ),
        migrations.RemoveField(
            model_name='banggia',
            name='san_pham',
        ),
        migrations.RemoveField(
            model_name='bienthe',
            name='san_pham',
        ),
        migrations.RemoveField(
            model_name='donhang',
            name='khach_hang',
        ),
        migrations.RemoveField(
            model_name='donvitinh',
            name='san_pham',
        ),
        migrations.RemoveField(
            model_name='khachhang',
            name='nguoi_dung',
        ),
        migrations.DeleteModel(
            name='NhanVien',
        ),
        migrations.RemoveField(
            model_name='sanpham',
            name='loai_san_pham',
        ),
        migrations.RemoveField(
            model_name='sanpham',
            name='nha_cung_cap',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.DeleteModel(
            name='BangGia',
        ),
        migrations.DeleteModel(
            name='BienThe',
        ),
        migrations.DeleteModel(
            name='DonHang',
        ),
        migrations.DeleteModel(
            name='DonViTinh',
        ),
        migrations.DeleteModel(
            name='KhachHang',
        ),
        migrations.DeleteModel(
            name='LoaiSanPham',
        ),
        migrations.DeleteModel(
            name='NhaCungCap',
        ),
        migrations.DeleteModel(
            name='SanPham',
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='management.producttype'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='management.supplier'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricelists', to='management.product', verbose_name='Sản phẩm'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricelists', to='management.unit', verbose_name='Đơn vị tính'),
        ),
        migrations.AddField(
            model_name='customer',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
