# Generated by Django 4.0.7 on 2022-09-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_supplier_address_alter_supplier_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroup',
            name='description',
            field=models.TextField(help_text='Mô tả của nhóm sản phẩm', null=True, verbose_name='Mô tả nhóm sản phẩm'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='note',
            field=models.TextField(help_text='Ghi chú nội bộ', null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='product_group_code',
            field=models.CharField(max_length=15, verbose_name='Mã nhóm sản phẩm'),
        ),
    ]
