# Generated by Django 4.0.7 on 2022-09-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_productgroup_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationunit',
            name='note',
            field=models.TextField(help_text='Ghi chú nội bộ', null=True, verbose_name='Ghi chú'),
        ),
    ]
