# Generated by Django 4.0.7 on 2022-08-25 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_customertype_inventoryreceivingvoucher_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customertype',
            table='CustomerType',
        ),
        migrations.AlterModelTable(
            name='inventoryreceivingvoucher',
            table='InventoryReceivingVoucher',
        ),
        migrations.AlterModelTable(
            name='inventoryreceivingvoucherdetail',
            table='InventoryReceivingVoucherDetail',
        ),
        migrations.AlterModelTable(
            name='inventoryvoucher',
            table='InventoryVoucher',
        ),
        migrations.AlterModelTable(
            name='inventoryvoucherdetail',
            table='InventoryVoucherDetail',
        ),
        migrations.AlterModelTable(
            name='orderdetail',
            table='OrderDetail',
        ),
        migrations.AlterModelTable(
            name='promotion',
            table='Promotion',
        ),
        migrations.AlterModelTable(
            name='promotionfixedvoucher',
            table='PromotionFixedVoucher',
        ),
        migrations.AlterModelTable(
            name='promotionpercentvoucher',
            table='PromotionPercentVoucher',
        ),
        migrations.AlterModelTable(
            name='promotionproductvoucher',
            table='PromotionProductVoucher',
        ),
    ]
