# Generated by Django 4.0.7 on 2022-09-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_calculationunit_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=True, verbose_name='Mô tả sản phẩm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=255, null=True, verbose_name='Hình ảnh sản phẩm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(max_length=15, verbose_name='Mã sản phẩm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_groups',
            field=models.ManyToManyField(blank=True, db_table='ProductGroupDetail', related_name='products', to='management.productgroup'),
        ),
    ]
