# Generated by Django 4.0.7 on 2022-08-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_customer_account_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Mã khách hàng'),
        ),
    ]
