# Generated by Django 4.0.7 on 2022-09-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_product_description_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='units',
            field=models.ManyToManyField(related_name='units', through='management.UnitExchange', to='management.calculationunit'),
        ),
    ]
