# Generated by Django 4.0.7 on 2022-08-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_customer_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Mã khách hàng'),
        ),
        migrations.AlterField(
            model_name='inventoryreceivingvoucher',
            name='voucher_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Mã phiếu nhập hàng'),
        ),
        migrations.AlterField(
            model_name='inventoryvoucher',
            name='voucher_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Mã phiếu kiểm kê'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Mã đơn hàng'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Mã sản phẩm'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='product_type_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Mã loại sản phẩm'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Mã nhân viên'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Mã nhà cung cấp'),
        ),
    ]
