# Generated by Django 4.0.7 on 2022-09-14 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_product_base_unit_alter_product_units_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricedetail',
            name='pricelist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricedetails', to='management.pricelist'),
        ),
        migrations.AlterField(
            model_name='pricedetail',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pricedetails', to='management.product', verbose_name='Sản phẩm'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricedetail',
            name='unit_exchange',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pricedetails', to='management.unitexchange', verbose_name='Đơn vị tính'),
            preserve_default=False,
        ),
    ]
