# Generated by Django 4.0.7 on 2022-09-14 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_alter_pricedetail_pricelist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_unit',
            field=models.ForeignKey(default=5, help_text='Đơn vị cơ bản', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='management.calculationunit', verbose_name='Đơn vị cơ bản'),
            preserve_default=False,
        ),
    ]
