# Generated by Django 4.0.7 on 2022-08-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_customer_gender_staff_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(max_length=15, unique=True, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Trạng thái'),
        ),
        migrations.AlterModelTable(
            name='customertype',
            table='CustomerGroup',
        ),
    ]
