# Generated by Django 4.0.7 on 2022-09-14 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_alter_product_base_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricedetail',
            name='unit_exchange',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricedetails', to='management.unitexchange', verbose_name='Đơn vị tính'),
        ),
    ]
