# Generated by Django 4.0.7 on 2022-09-14 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_alter_pricedetail_unit_exchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Trạng thái'),
        ),
    ]
