# Generated by Django 4.0.7 on 2022-08-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_rename_customertype_customergroup_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductType',
            new_name='ProductGroup',
        ),
        migrations.RenameField(
            model_name='promotionproductvoucher',
            old_name='applicable_product_types',
            new_name='applicable_product_groups',
        ),
        migrations.AlterField(
            model_name='promotion',
            name='applicable_customer_groups',
            field=models.ManyToManyField(db_table='ApplicableCustomerGroup', to='management.customergroup'),
        ),
        migrations.AlterModelTable(
            name='productgroup',
            table='ProductGroup',
        ),
    ]
