# Generated by Django 4.0.7 on 2022-09-18 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_alter_pricelist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryreceivingvoucher',
            name='total',
            field=models.FloatField(default=0, verbose_name='Thành tiền'),
        ),
        migrations.AlterField(
            model_name='inventoryreceivingvoucherdetail',
            name='receiving_voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='management.inventoryreceivingvoucher'),
        ),
    ]
