# Generated by Django 4.0.7 on 2022-08-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_rename_producttype_productgroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionproductvoucher',
            name='applicable_product_groups',
            field=models.ManyToManyField(db_table='ApplicableProductGroup', to='management.productgroup'),
        ),
    ]
