# Generated by Django 4.0.7 on 2022-09-19 13:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_alter_inventoryreceivingvoucher_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotiondetail',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='promotiondetail',
            name='max_quantity',
        ),
        migrations.RemoveField(
            model_name='promotiondetail',
            name='max_quantity_per_customer',
        ),
        migrations.RemoveField(
            model_name='promotiondetail',
            name='max_quantity_per_customer_per_day',
        ),
        migrations.RemoveField(
            model_name='promotiondetail',
            name='promotion',
        ),
        migrations.RemoveField(
            model_name='promotiondetail',
            name='promotion_code',
        ),
        migrations.RemoveField(
            model_name='promotiondetail',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='promotiondetail',
            name='status',
        ),
        migrations.RemoveField(
            model_name='promotiondetail',
            name='type',
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Trạng thái'),
        ),
        migrations.CreateModel(
            name='PromotionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_code', models.CharField(max_length=15, null=True, unique=True, verbose_name='Mã khuyến mãi')),
                ('type', models.CharField(choices=[('Product', 'Khuyến mãi sản phẩm'), ('Percent', 'Khuyến mãi theo phần trăm hóa đơn'), ('Fixed', 'Khuyến mãi số tiền nhất định')], max_length=15, verbose_name='Loại khuyến mãi')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian bắt đầu áp dụng')),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian kết thúc')),
                ('status', models.BooleanField(verbose_name='Trạng thái')),
                ('max_quantity', models.IntegerField(null=True, verbose_name='Số lần áp dụng tối đa')),
                ('max_quantity_per_customer', models.IntegerField(null=True, verbose_name='Số lần áp dụng tối đa trên khách hàng')),
                ('max_quantity_per_customer_per_day', models.IntegerField(null=True, verbose_name='Số lần áp dụng tối đa trên khách hàng trên 1 ngày')),
                ('promotion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.promotion')),
            ],
        ),
        migrations.AddField(
            model_name='promotiondetail',
            name='promotion_line',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.promotionline'),
        ),
    ]
