# Generated by Django 4.0.7 on 2022-08-27 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_alter_promotionproductvoucher_applicable_product_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricelist',
            name='price',
        ),
        migrations.RemoveField(
            model_name='pricelist',
            name='product',
        ),
        migrations.RemoveField(
            model_name='pricelist',
            name='unit',
        ),
        migrations.AddField(
            model_name='pricelist',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Trạng thái'),
        ),
        migrations.CreateModel(
            name='PriceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.pricelist')),
            ],
        ),
    ]
