# Generated by Django 4.0.7 on 2022-09-19 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_remove_promotiondetail_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryvoucherdetail',
            name='inventory_voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='management.inventoryvoucher'),
        ),
        migrations.AlterField(
            model_name='warehousetransaction',
            name='type',
            field=models.CharField(choices=[('order', 'Bán hàng'), ('inventory', 'Kiểm kê'), ('inventory_receiving', 'Nhập hàng'), ('inventory_receiving_cancel', 'Hủy nhập hàng'), ('refund', 'Trả hàng')], max_length=30, verbose_name='Loại biến động'),
        ),
    ]
