# Generated by Django 4.0.7 on 2022-09-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_alter_inventoryvoucherdetail_inventory_voucher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryvoucherdetail',
            name='note',
            field=models.TextField(null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='inventoryvoucherdetail',
            name='quantity_before',
            field=models.PositiveIntegerField(null=True, verbose_name='Số lượng trước'),
        ),
    ]
