# Generated by Django 4.0.7 on 2022-09-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_alter_inventoryvoucherdetail_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryreceivingvoucherdetail',
            name='unit_exchange',
        ),
        migrations.RemoveField(
            model_name='inventoryvoucherdetail',
            name='unit_exchange',
        ),
        migrations.RemoveField(
            model_name='warehousetransaction',
            name='unit_exchange',
        ),
        migrations.AlterField(
            model_name='warehousetransaction',
            name='type',
            field=models.CharField(choices=[('order', 'Bán hàng'), ('inventory', 'Kiểm kê'), ('inventory_cancel', 'Hủy kiểm kê'), ('inventory_receiving', 'Nhập hàng'), ('inventory_receiving_cancel', 'Hủy nhập hàng'), ('refund', 'Trả hàng')], max_length=30, verbose_name='Loại biến động'),
        ),
    ]
