# Generated by Django 4.0.7 on 2022-08-27 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_remove_promotion_type_alter_promotion_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.IntegerField(verbose_name='Thay đổi')),
                ('type', models.CharField(choices=[('order', 'Bán hàng'), ('inventory', 'Kiểm kê'), ('inventory_receiving', 'Nhập hàng'), ('refund', 'Trả hàng')], max_length=30, verbose_name='Loại biến động')),
                ('inventory_voucher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='management.inventoryvoucher')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='management.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.product')),
                ('receiving_voucher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='management.inventoryreceivingvoucher')),
            ],
        ),
    ]
