# Generated by Django 4.0.7 on 2022-08-27 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_warehousetransaction'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pricedetail',
            table='PriceDetail',
        ),
        migrations.AlterModelTable(
            name='promotionhistory',
            table='PromotionHistory',
        ),
        migrations.AlterModelTable(
            name='warehousetransaction',
            table='WarehouseTransaction',
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('refund_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã trả hàng')),
                ('note', models.TextField(verbose_name='Ghi chú')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.order')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='management.staff')),
            ],
            options={
                'db_table': 'Refund',
            },
        ),
    ]
