# Generated by Django 4.0.7 on 2022-09-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_alter_hierarchytree_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(max_length=30, null=True, verbose_name='Tên nhân viên'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='Số điện thoại')),
                ('fullname', models.CharField(max_length=30, null=True, verbose_name='Tên khách hàng')),
                ('gender', models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ'), ('U', 'Không xác định')], default='U', max_length=1, verbose_name='Giới tính')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='Địa chỉ')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('customer_group', models.ManyToManyField(blank=True, db_table='CustomerGroupDetail2', related_name='customer_group_detail2', to='management.customergroup')),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
    ]
