# Generated by Django 4.0.7 on 2022-09-20 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_alter_user_fullname_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='customer_group',
        ),
    ]
