# Generated by Django 4.0.7 on 2022-08-27 15:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_remove_inventoryreceivingvoucherdetail_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.FloatField(default=0, verbose_name='Thành tiền'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.unit', verbose_name='Đơn vị tính'),
        ),
        migrations.AlterField(
            model_name='inventoryreceivingvoucher',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 15, 0, 36, 930968, tzinfo=utc), verbose_name='Ngày nhập hàng'),
        ),
        migrations.AlterField(
            model_name='inventoryvoucher',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 15, 0, 36, 931830, tzinfo=utc), verbose_name='Ngày tạo phiếu kiểm kê'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 15, 0, 36, 916929, tzinfo=utc), verbose_name='Ngày lập hóa đơn'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.pricedetail'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='total',
            field=models.FloatField(default=0, verbose_name='Thành tiền'),
        ),
        migrations.AlterField(
            model_name='pricedetail',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricedetails', to='management.product', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='pricedetail',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricedetails', to='management.unit', verbose_name='Đơn vị tính'),
        ),
        migrations.AlterField(
            model_name='promotionhistory',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 15, 0, 36, 936530, tzinfo=utc), verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 15, 0, 36, 930508, tzinfo=utc), verbose_name='Ngày trả hàng'),
        ),
        migrations.AlterField(
            model_name='warehousetransaction',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 15, 0, 36, 932764, tzinfo=utc), verbose_name='Ngày tạo'),
        ),
    ]
