# Generated by Django 4.0.7 on 2022-08-27 15:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_order_total_orderdetail_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryvoucher',
            name='status',
        ),
        migrations.RemoveField(
            model_name='warehousetransaction',
            name='inventory_voucher',
        ),
        migrations.RemoveField(
            model_name='warehousetransaction',
            name='order',
        ),
        migrations.RemoveField(
            model_name='warehousetransaction',
            name='receiving_voucher',
        ),
        migrations.AddField(
            model_name='warehousetransaction',
            name='inventory_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='management.inventoryvoucherdetail'),
        ),
        migrations.AddField(
            model_name='warehousetransaction',
            name='inventory_receiving_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='management.inventoryreceivingvoucherdetail'),
        ),
        migrations.AddField(
            model_name='warehousetransaction',
            name='order_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='management.orderdetail'),
        ),
        migrations.AddField(
            model_name='warehousetransaction',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='management.unit'),
        ),
        migrations.AlterField(
            model_name='inventoryreceivingvoucher',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 15, 9, 35, 112284, tzinfo=utc), verbose_name='Ngày nhập hàng'),
        ),
        migrations.AlterField(
            model_name='inventoryreceivingvoucher',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('complete', 'Hoàn thành')], max_length=15, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='inventoryvoucher',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 15, 9, 35, 113199, tzinfo=utc), verbose_name='Ngày tạo phiếu kiểm kê'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 15, 9, 35, 97848, tzinfo=utc), verbose_name='Ngày lập hóa đơn'),
        ),
        migrations.AlterField(
            model_name='promotionhistory',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 15, 9, 35, 118592, tzinfo=utc), verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 15, 9, 35, 111761, tzinfo=utc), verbose_name='Ngày trả hàng'),
        ),
        migrations.AlterField(
            model_name='warehousetransaction',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 15, 9, 35, 114185, tzinfo=utc), verbose_name='Ngày tạo'),
        ),
    ]
