# Generated by Django 4.0.7 on 2022-08-27 15:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_remove_inventoryvoucher_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryreceivingvoucher',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày nhập hàng'),
        ),
        migrations.AlterField(
            model_name='inventoryvoucher',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo phiếu kiểm kê'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày lập hóa đơn'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Thời gian kết thúc áp dụng bảng giá', verbose_name='Thời gian kết thúc'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Thời gian bắt đâu áp dụng bảng giá', verbose_name='Thời gian bắt đầu'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian kết thúc'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian bắt đầu áp dụng'),
        ),
        migrations.AlterField(
            model_name='promotionhistory',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày trả hàng'),
        ),
        migrations.AlterField(
            model_name='warehousetransaction',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo'),
        ),
    ]
