# Generated by Django 4.0.7 on 2022-08-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0023_alter_inventoryreceivingvoucher_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HierarchyTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tên cấp')),
                ('level', models.IntegerField(default=0, verbose_name='Cấp')),
                ('type', models.CharField(choices=[('product', 'Sản phẩm')], max_length=15, verbose_name='Loại')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Đang chờ'), ('complete', 'Hoàn tất'), ('cancel', 'Đã hủy đơn / hoàn trả')], default='pending', max_length=15, verbose_name='Trạng thái'),
        ),
    ]
