# Generated by Django 4.0.7 on 2022-08-27 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0024_hierarchytree_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hierarchytree',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.hierarchytree'),
        ),
        migrations.AlterModelTable(
            name='hierarchytree',
            table='HierarchyTree',
        ),
    ]
