# Generated by Django 4.0.7 on 2022-09-21 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0024_alter_promotiondetail_promotion_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionline',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Tiêu đề của khuyến mãi'),
        ),
    ]
