# Generated by Django 4.0.7 on 2022-09-21 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0025_promotionline_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionline',
            name='description',
            field=models.TextField(default='', verbose_name='Mô tả khuyến mãi'),
        ),
    ]
