# Generated by Django 4.0.7 on 2022-09-21 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0026_promotionline_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotiondetail',
            name='applicable_product_groups',
            field=models.ManyToManyField(db_table='ApplicableProductGroup', null=True, to='management.productgroup'),
        ),
        migrations.AlterField(
            model_name='promotiondetail',
            name='applicable_products',
            field=models.ManyToManyField(db_table='ApplicableProduct', null=True, to='management.product'),
        ),
    ]
