# Generated by Django 4.0.7 on 2022-08-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0027_product_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='promotion_code',
        ),
        migrations.AddField(
            model_name='promotionfixedvoucher',
            name='promotion_code',
            field=models.CharField(max_length=15, null=True, verbose_name='Mã khuyến mãi'),
        ),
        migrations.AddField(
            model_name='promotionpercentvoucher',
            name='promotion_code',
            field=models.CharField(max_length=15, null=True, verbose_name='Mã khuyến mãi'),
        ),
        migrations.AddField(
            model_name='promotionproductvoucher',
            name='promotion_code',
            field=models.CharField(max_length=15, null=True, verbose_name='Mã khuyến mãi'),
        ),
    ]
