# Generated by Django 4.0.7 on 2022-09-21 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0027_alter_promotiondetail_applicable_product_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionline',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='management.promotion'),
        ),
    ]
