# Generated by Django 4.0.7 on 2022-09-21 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0028_alter_promotionline_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotiondetail',
            name='product_received',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_receive', to='management.product'),
        ),
    ]
