# Generated by Django 4.0.7 on 2022-08-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0028_remove_promotion_promotion_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionhistory',
            name='reduction_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Số lượng sản phẩm được nhận'),
        ),
    ]
