# Generated by Django 4.0.7 on 2022-08-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0029_promotionhistory_reduction_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=255, null=True, verbose_name='Địa chỉ'),
        ),
    ]
