# Generated by Django 4.0.7 on 2022-09-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0029_promotiondetail_product_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='hierarchytree',
            name='note',
            field=models.TextField(null=True, verbose_name='Ghi chú'),
        ),
        migrations.AddField(
            model_name='history',
            name='note',
            field=models.TextField(null=True, verbose_name='Ghi chú'),
        ),
        migrations.AddField(
            model_name='pricedetail',
            name='note',
            field=models.TextField(null=True, verbose_name='Ghi chú'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='note',
            field=models.TextField(null=True, verbose_name='Ghi chú'),
        ),
        migrations.AddField(
            model_name='product',
            name='note',
            field=models.TextField(null=True, verbose_name='Ghi chú'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='note',
            field=models.TextField(null=True, verbose_name='Ghi chú'),
        ),
        migrations.AddField(
            model_name='promotionhistory',
            name='note',
            field=models.TextField(null=True, verbose_name='Ghi chú'),
        ),
        migrations.AddField(
            model_name='promotionline',
            name='note',
            field=models.TextField(null=True, verbose_name='Ghi chú'),
        ),
        migrations.AddField(
            model_name='warehousetransaction',
            name='note',
            field=models.TextField(null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='note',
            field=models.TextField(null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='note',
            field=models.TextField(null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='inventoryreceivingvoucher',
            name='note',
            field=models.TextField(null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='inventoryreceivingvoucherdetail',
            name='note',
            field=models.TextField(null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='inventoryvoucher',
            name='note',
            field=models.TextField(null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='note',
            field=models.TextField(null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='orderrefund',
            name='note',
            field=models.TextField(null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='orderrefunddetail',
            name='note',
            field=models.TextField(null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='note',
            field=models.TextField(null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='note',
            field=models.TextField(null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='user',
            name='note',
            field=models.TextField(null=True, verbose_name='Ghi chú'),
        ),
    ]
