# Generated by Django 4.0.7 on 2022-09-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0030_customer_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='type',
        ),
        migrations.AddField(
            model_name='customer',
            name='type',
            field=models.ManyToManyField(to='management.customergroup'),
        ),
    ]
