# Generated by Django 4.0.7 on 2022-09-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0031_remove_customer_type_customer_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='type',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_group',
            field=models.ManyToManyField(db_table='CustomerGroupDetail', to='management.customergroup'),
        ),
    ]
