# Generated by Django 4.0.7 on 2022-09-03 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0032_remove_customer_type_customer_customer_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryreceivingvoucherdetail',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='inventoryvoucherdetail',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='pricedetail',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='allow_sale',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='is_base_unit',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='product',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='value',
        ),
        migrations.RemoveField(
            model_name='warehousetransaction',
            name='unit',
        ),
        migrations.CreateModel(
            name='UnitExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(help_text='Đơn vị này bằng bao nhiêu đơn vị mặc định?', verbose_name='Giá trị quy đổi')),
                ('allow_sale', models.BooleanField(help_text='Cho phép bán hàng bằng đơn vị này không?', verbose_name='Đơn vị được phép bán hàng')),
                ('is_base_unit', models.BooleanField(help_text='Có phải là đơn vị cơ bản hay không (đơn vị nhỏ nhất)', verbose_name='Đơn vị cơ bản')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unitexchanges', to='management.product')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unitexchanges', to='management.unit')),
            ],
        ),
        migrations.AddField(
            model_name='inventoryreceivingvoucherdetail',
            name='unit_exchange',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='management.unitexchange'),
        ),
        migrations.AddField(
            model_name='inventoryvoucherdetail',
            name='unit_exchange',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='management.unitexchange'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='unit_exchange',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.unitexchange', verbose_name='Đơn vị tính'),
        ),
        migrations.AddField(
            model_name='pricedetail',
            name='unit_exchange',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricedetails', to='management.unitexchange', verbose_name='Đơn vị tính'),
        ),
        migrations.AddField(
            model_name='warehousetransaction',
            name='UnitExchange',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='management.unitexchange'),
        ),
    ]
