# Generated by Django 4.0.7 on 2022-09-03 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0033_remove_inventoryreceivingvoucherdetail_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitexchange',
            name='is_base_unit',
        ),
        migrations.AddField(
            model_name='product',
            name='base_unit',
            field=models.ForeignKey(help_text='Đơn vị cơ bản', null=True, on_delete=django.db.models.deletion.CASCADE, to='management.unit', verbose_name='Đơn vị cơ bản'),
        ),
    ]
