# Generated by Django 4.0.7 on 2022-09-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0034_promotionline_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='base_unit',
        ),
        migrations.AddField(
            model_name='unitexchange',
            name='is_base_unit',
            field=models.BooleanField(default=False, verbose_name='Đơn vị cơ bản'),
        ),
    ]
