# Generated by Django 4.0.7 on 2022-09-03 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0034_remove_unitexchange_is_base_unit_product_base_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(max_length=50, verbose_name='Tên đối tượng')),
                ('object_id', models.CharField(max_length=50, verbose_name='Mã đối tượng')),
                ('action', models.CharField(choices=[('CREATE', 'Tạo mới'), ('UPDATE', 'Cập nhật'), ('DELETE', 'Xóa')], max_length=15, verbose_name='Hành động')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
            ],
        ),
    ]
