# Generated by Django 4.0.7 on 2022-09-22 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0036_customergroup_date_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='user_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_group_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='user_updated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_group_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
