# Generated by Django 4.0.7 on 2022-09-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0037_productgroup_date_updated_productgroup_user_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroup',
            name='date_updated',
            field=models.DateTimeField(null=True, verbose_name='Ngày cập nhật'),
        ),
    ]
