# Generated by Django 4.1.1 on 2022-09-06 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0037_alter_customer_account_alter_order_customer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='NguoiDung',
        ),
    ]
