# Generated by Django 4.1.1 on 2022-09-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0038_alter_user_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_group',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='note',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=255, null=True, verbose_name='Địa chỉ'),
        ),
        migrations.AddField(
            model_name='user',
            name='customer_group',
            field=models.ManyToManyField(db_table='CustomerGroupDetail', to='management.customergroup'),
        ),
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(max_length=30, null=True, verbose_name='Tên khách hàng'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ'), ('U', 'Không xác định')], default='U', max_length=1, verbose_name='Giới tính'),
        ),
        migrations.AddField(
            model_name='user',
            name='note',
            field=models.TextField(blank=True, verbose_name='Ghi chú'),
        ),
    ]
