# Generated by Django 4.0.7 on 2022-09-22 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0038_alter_productgroup_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationunit',
            name='date_updated',
            field=models.DateTimeField(null=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='calculationunit',
            name='user_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='units_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calculationunit',
            name='user_updated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='units_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='date_updated',
            field=models.DateTimeField(null=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='user_updated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hierarchytree',
            name='date_updated',
            field=models.DateTimeField(null=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='hierarchytree',
            name='user_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hierarchy_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hierarchytree',
            name='user_updated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hierarchy_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày cập nhật hóa đơn'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='user_updated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderrefund',
            name='date_updated',
            field=models.DateTimeField(null=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='orderrefund',
            name='user_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_refund_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderrefund',
            name='user_updated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_refund_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='date_updated',
            field=models.DateTimeField(null=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='user_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pricelists_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='user_updated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pricelists_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='date_updated',
            field=models.DateTimeField(null=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='product',
            name='user_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='user_updated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplier',
            name='date_updated',
            field=models.DateTimeField(null=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='user_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suppliers_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplier',
            name='user_updated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suppliers_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unitexchange',
            name='date_updated',
            field=models.DateTimeField(null=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='unitexchange',
            name='user_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit_exchange_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unitexchange',
            name='user_updated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit_exchange_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='date_updated',
            field=models.DateTimeField(null=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='user_updated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='date_updated',
            field=models.DateTimeField(null=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='user_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_group_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='user_updated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_group_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
