# Generated by Django 4.0.7 on 2022-09-22 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0039_calculationunit_date_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryreceivingvoucher',
            name='date_updated',
            field=models.DateTimeField(null=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='inventoryreceivingvoucher',
            name='user_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_receiving_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryreceivingvoucher',
            name='user_updated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_receiving_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryvoucher',
            name='date_updated',
            field=models.DateTimeField(null=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='inventoryvoucher',
            name='user_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryvoucher',
            name='user_updated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotion',
            name='date_updated',
            field=models.DateTimeField(null=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='user_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotion',
            name='user_updated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotions_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotionline',
            name='date_updated',
            field=models.DateTimeField(null=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='promotionline',
            name='user_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotion_lines_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotionline',
            name='user_updated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotion_lines_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
