# Generated by Django 4.1.1 on 2022-09-06 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0040_alter_order_staff_alter_refund_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
