# Generated by Django 4.1.1 on 2022-09-06 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0041_delete_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
