# Generated by Django 4.0.7 on 2022-09-26 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0042_alter_orderdetail_unit_exchange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderrefund',
            name='staff',
        ),
    ]
