# Generated by Django 4.0.7 on 2022-09-06 14:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0042_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_code', models.CharField(max_length=15, null=True, verbose_name='Mã khuyến mãi')),
                ('type', models.CharField(choices=[('Product', 'Khuyến mãi sản phẩm'), ('Percent', 'Khuyến mãi theo phần trăm hóa đơn'), ('Fixed', 'Khuyến mãi số tiền nhất định')], max_length=15, verbose_name='Loại khuyến mãi')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian bắt đầu áp dụng')),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian kết thúc')),
                ('status', models.BooleanField(verbose_name='Trạng thái')),
                ('max_quantity', models.IntegerField(verbose_name='Số lần áp dụng tối đa')),
                ('max_quantity_per_customer', models.IntegerField(verbose_name='Số lần áp dụng tối đa trên khách hàng')),
                ('max_quantity_per_customer_per_day', models.IntegerField(verbose_name='Số lần áp dụng tối đa trên khách hàng trên 1 ngày')),
                ('quantity_buy', models.PositiveIntegerField(verbose_name='Số lượng sản phẩm cần mua')),
                ('quantity_received', models.PositiveIntegerField(verbose_name='Số lượng sản phẩm được nhận')),
                ('minimum_total', models.FloatField(verbose_name='Số tiền tối thiểu trên hóa đơn')),
                ('percent', models.FloatField(verbose_name='Phần trăm giảm giá')),
                ('maximum_reduction_amount', models.FloatField(verbose_name='Số tiền được giảm tối đa')),
                ('reduction_amount', models.FloatField(verbose_name='Số tiền được giảm')),
                ('applicable_product_groups', models.ManyToManyField(db_table='ApplicableProductGroup2', to='management.productgroup')),
                ('applicable_products', models.ManyToManyField(db_table='ApplicableProduct2', to='management.product')),
            ],
            options={
                'db_table': 'PromotionDetail',
            },
        ),
        migrations.RemoveField(
            model_name='promotionpercentvoucher',
            name='promotion',
        ),
        migrations.RemoveField(
            model_name='promotionproductvoucher',
            name='applicable_product_groups',
        ),
        migrations.RemoveField(
            model_name='promotionproductvoucher',
            name='applicable_products',
        ),
        migrations.RemoveField(
            model_name='promotionproductvoucher',
            name='promotion',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='max_quantity',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='max_quantity_per_customer',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='max_quantity_per_customer_per_day',
        ),
        migrations.RemoveField(
            model_name='promotionhistory',
            name='fixed_voucher',
        ),
        migrations.RemoveField(
            model_name='promotionhistory',
            name='percent_voucher',
        ),
        migrations.RemoveField(
            model_name='promotionhistory',
            name='product_voucher',
        ),
        migrations.RemoveField(
            model_name='promotionhistory',
            name='type',
        ),
        migrations.AddField(
            model_name='history',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
        migrations.DeleteModel(
            name='PromotionFixedVoucher',
        ),
        migrations.DeleteModel(
            name='PromotionPercentVoucher',
        ),
        migrations.DeleteModel(
            name='PromotionProductVoucher',
        ),
        migrations.AddField(
            model_name='promotiondetail',
            name='promotion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.promotion'),
        ),
        migrations.AddField(
            model_name='promotionhistory',
            name='promotion_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='management.promotiondetail'),
        ),
    ]
