# Generated by Django 4.0.7 on 2022-09-26 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0043_remove_orderrefund_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrefund',
            name='status',
            field=models.CharField(choices=[('pending', 'Đang chờ'), ('complete', 'Hoàn tất'), ('cancel', 'Hủy')], default='pending', max_length=15, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='orderrefund',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund', to='management.order'),
        ),
        migrations.AlterField(
            model_name='orderrefunddetail',
            name='order_refund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='management.orderrefund'),
        ),
        migrations.AlterField(
            model_name='orderrefunddetail',
            name='unit_exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.unitexchange', verbose_name='Đơn vị tính'),
        ),
    ]
