# Generated by Django 4.0.7 on 2022-09-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0043_promotiondetail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotiondetail',
            name='applicable_product_groups',
            field=models.ManyToManyField(db_table='ApplicableProductGroup', null=True, to='management.productgroup'),
        ),
        migrations.AlterField(
            model_name='promotiondetail',
            name='applicable_products',
            field=models.ManyToManyField(db_table='ApplicableProduct', null=True, to='management.product'),
        ),
        migrations.AlterField(
            model_name='promotiondetail',
            name='max_quantity',
            field=models.IntegerField(null=True, verbose_name='Số lần áp dụng tối đa'),
        ),
        migrations.AlterField(
            model_name='promotiondetail',
            name='max_quantity_per_customer',
            field=models.IntegerField(null=True, verbose_name='Số lần áp dụng tối đa trên khách hàng'),
        ),
        migrations.AlterField(
            model_name='promotiondetail',
            name='max_quantity_per_customer_per_day',
            field=models.IntegerField(null=True, verbose_name='Số lần áp dụng tối đa trên khách hàng trên 1 ngày'),
        ),
        migrations.AlterField(
            model_name='promotiondetail',
            name='maximum_reduction_amount',
            field=models.FloatField(null=True, verbose_name='Số tiền được giảm tối đa'),
        ),
        migrations.AlterField(
            model_name='promotiondetail',
            name='minimum_total',
            field=models.FloatField(null=True, verbose_name='Số tiền tối thiểu trên hóa đơn'),
        ),
        migrations.AlterField(
            model_name='promotiondetail',
            name='percent',
            field=models.FloatField(null=True, verbose_name='Phần trăm giảm giá'),
        ),
        migrations.AlterField(
            model_name='promotiondetail',
            name='quantity_buy',
            field=models.PositiveIntegerField(null=True, verbose_name='Số lượng sản phẩm cần mua'),
        ),
        migrations.AlterField(
            model_name='promotiondetail',
            name='quantity_received',
            field=models.PositiveIntegerField(null=True, verbose_name='Số lượng sản phẩm được nhận'),
        ),
        migrations.AlterField(
            model_name='promotiondetail',
            name='reduction_amount',
            field=models.FloatField(null=True, verbose_name='Số tiền được giảm'),
        ),
    ]
