# Generated by Django 4.0.7 on 2022-09-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0044_orderrefund_status_alter_orderrefund_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrefund',
            name='status',
            field=models.CharField(choices=[('complete', 'Hoàn tất'), ('cancel', 'Hủy')], default='pending', max_length=15, verbose_name='Trạng thái'),
        ),
    ]
