# Generated by Django 4.0.7 on 2022-09-06 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0045_calculationunit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehousetransaction',
            old_name='UnitExchange',
            new_name='unit_exchange',
        ),
        migrations.RemoveField(
            model_name='warehousetransaction',
            name='inventory_detail',
        ),
        migrations.RemoveField(
            model_name='warehousetransaction',
            name='inventory_receiving_detail',
        ),
        migrations.RemoveField(
            model_name='warehousetransaction',
            name='order_detail',
        ),
    ]
