# Generated by Django 4.0.7 on 2022-09-30 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0045_alter_orderrefund_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionhistory',
            name='promotion_detail',
        ),
        migrations.AddField(
            model_name='promotiondetail',
            name='unit_buy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_unit_buy', to='management.unitexchange'),
        ),
        migrations.AddField(
            model_name='promotiondetail',
            name='unit_received',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_unit_received', to='management.unitexchange'),
        ),
        migrations.AddField(
            model_name='promotionhistory',
            name='promotion_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='management.promotionline'),
        ),
    ]
