# Generated by Django 4.0.7 on 2022-09-06 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0046_rename_unitexchange_warehousetransaction_unit_exchange_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderrefund',
            table='OrderRefund',
        ),
    ]
