# Generated by Django 4.0.7 on 2022-09-30 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0046_remove_promotionhistory_promotion_detail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotionhistory',
            old_name='reduction_amount',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='promotionhistory',
            name='reduction_quantity',
        ),
        migrations.AddField(
            model_name='promotionhistory',
            name='quantity',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Số lượng khuyến mãi'),
        ),
        migrations.AddField(
            model_name='promotionhistory',
            name='type',
            field=models.CharField(choices=[('Order', 'Hóa đơn'), ('Product', 'Sản phẩm')], default=None, max_length=15, verbose_name='Loại'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promotionhistory',
            name='promotion_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='histories', to='management.promotionline'),
        ),
    ]
