# Generated by Django 4.0.7 on 2022-09-06 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0047_alter_orderrefund_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_type',
            new_name='product_category',
        ),
    ]
