# Generated by Django 4.0.7 on 2022-09-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0048_rename_product_type_product_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_group',
        ),
        migrations.AddField(
            model_name='product',
            name='product_groups',
            field=models.ManyToManyField(db_table='ProductGroupDetail', null=True, related_name='products', to='management.productgroup'),
        ),
    ]
