# Generated by Django 4.0.7 on 2022-10-02 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0048_alter_orderdetail_price_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='promotionline',
            table='PromotionLine',
        ),
    ]
