# Generated by Django 4.0.7 on 2022-09-06 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0049_remove_product_product_group_product_product_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='supplier_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='staff',
        ),
        migrations.AddField(
            model_name='calculationunit',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo'),
        ),
        migrations.AddField(
            model_name='calculationunit',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='calculationunit',
            name='user_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='units_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calculationunit',
            name='user_updated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='units_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hierarchytree',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo'),
        ),
        migrations.AddField(
            model_name='hierarchytree',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='hierarchytree',
            name='user_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hierarchy_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hierarchytree',
            name='user_updated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hierarchy_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryreceivingvoucher',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='inventoryreceivingvoucher',
            name='user_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_receiving_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryreceivingvoucher',
            name='user_updated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_receiving_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryvoucher',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='inventoryvoucher',
            name='user_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryvoucher',
            name='user_updated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày cập nhật hóa đơn'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='user_updated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderrefund',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='orderrefund',
            name='user_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_refund_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderrefund',
            name='user_updated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_refund_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='user_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pricelists_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='user_updated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pricelists_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo'),
        ),
        migrations.AddField(
            model_name='product',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='product',
            name='user_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='user_updated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo'),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='user_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_group_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='user_updated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_group_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotion',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='user_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotion',
            name='user_updated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotions_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplier',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='user_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suppliers_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplier',
            name='user_updated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suppliers_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unitexchange',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo'),
        ),
        migrations.AddField(
            model_name='unitexchange',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='unitexchange',
            name='user_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit_exchange_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unitexchange',
            name='user_updated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit_exchange_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='user_updated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventoryreceivingvoucher',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='inventoryvoucher',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='orderrefund',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo'),
        ),
    ]
