# Generated by Django 4.0.7 on 2022-10-02 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0049_alter_promotionline_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotiondetail',
            name='unit_buy',
        ),
    ]
