# Generated by Django 4.0.7 on 2022-09-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0050_rename_supplier_name_supplier_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_groups',
            field=models.ManyToManyField(db_table='ProductGroupDetail', related_name='products', to='management.productgroup'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='applicable_customer_groups',
            field=models.ManyToManyField(db_table='ApplicableCustomerGroup', to='management.customergroup'),
        ),
        migrations.AlterField(
            model_name='promotiondetail',
            name='applicable_product_groups',
            field=models.ManyToManyField(db_table='ApplicableProductGroup', to='management.productgroup'),
        ),
        migrations.AlterField(
            model_name='promotiondetail',
            name='applicable_products',
            field=models.ManyToManyField(db_table='ApplicableProduct', to='management.product'),
        ),
    ]
