# Generated by Django 4.0.7 on 2022-10-02 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0050_remove_promotiondetail_unit_buy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotiondetail',
            name='unit_received',
        ),
        migrations.RemoveField(
            model_name='promotionhistory',
            name='order_detail',
        ),
        migrations.AddField(
            model_name='promotionhistory',
            name='buy_order_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buy_order_detail', to='management.orderdetail'),
        ),
        migrations.AddField(
            model_name='promotionhistory',
            name='received_order_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_order_detail', to='management.orderdetail'),
        ),
    ]
