# Generated by Django 4.0.7 on 2022-10-02 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0051_remove_promotiondetail_unit_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_total',
            field=models.FloatField(default=0, verbose_name='Thành tiền'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.FloatField(default=0, verbose_name='Tổng tiền'),
        ),
    ]
