# Generated by Django 4.0.7 on 2022-10-08 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0052_order_final_total_alter_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='management.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('complete', 'Hoàn tất'), ('cancel', 'Đã hủy đơn / hoàn trả')], default='complete', max_length=15, verbose_name='Trạng thái'),
        ),
    ]
