# Generated by Django 4.0.7 on 2022-10-11 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vi_address', '0001_initial'),
        ('management', '0053_alter_order_customer_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vi_address.ward'),
        ),
        migrations.AlterField(
            model_name='hierarchytree',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='management.hierarchytree'),
        ),
    ]
