# Generated by Django 4.0.7 on 2022-10-12 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0054_customer_ward_alter_hierarchytree_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
