# Generated by Django 4.0.7 on 2022-10-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0057_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='Giá trị')),
                ('table', models.CharField(max_length=30, verbose_name='Bảng')),
            ],
        ),
    ]
