# Generated by Django 4.0.7 on 2022-10-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0059_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Mã nhân viên'),
        ),
        migrations.AlterModelTable(
            name='counterindex',
            table='CounterIndex',
        ),
    ]
