# Generated by Django 4.0.7 on 2022-10-16 16:51

from django.db import migrations, models
import management.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0061_supplier_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='code',
            field=models.CharField(default=management.models.unique_rand, max_length=10, unique=True, verbose_name='Mã code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(default=management.models.unique_rand, max_length=10, unique=True, verbose_name='Mã nhân viên'),
        ),
    ]
