# Generated by Django 4.0.7 on 2022-10-16 17:14

from django.db import migrations, models
import management.models

def random_code(apps, schema_editor):
    for i in management.models.CalculationUnit.objects.all():
        i.code=management.models.unique_rand()
        i.save()

class Migration(migrations.Migration):

    dependencies = [
        ('management', '0064_alter_hierarchytree_code_alter_supplier_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationunit',
            name='code',
            field=models.CharField(max_length=30, unique=False, verbose_name='Mã code'),
        ),
        migrations.RunPython(random_code),
        migrations.AlterField(
            model_name='calculationunit',
            name='code',
            field=models.CharField(max_length=30, unique=True, verbose_name='Mã code'),
        ),
    ]
