# Generated by Django 4.0.7 on 2022-10-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0065_calculationunit_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationunit',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Tên đơn vị tính'),
        ),
    ]
