# Generated by Django 4.0.7 on 2022-10-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0066_alter_calculationunit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('complete', 'Hoàn tất'), ('cancel', 'Đã hủy đơn'), ('refund', 'Đã trả đơn')], default='complete', max_length=15, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='warehousetransaction',
            name='type',
            field=models.CharField(choices=[('order', 'Bán hàng'), ('order_cancel', 'Hủy hóa đơn'), ('promotion', 'Khuyến mãi'), ('inventory', 'Kiểm kê'), ('inventory_cancel', 'Hủy kiểm kê'), ('inventory_receiving', 'Nhập hàng'), ('inventory_receiving_cancel', 'Hủy nhập hàng'), ('refund', 'Trả hàng')], max_length=30, verbose_name='Loại biến động'),
        ),
    ]
