# Generated by Django 4.0.7 on 2022-10-17 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vi_address', '0001_initial'),
        ('management', '0067_alter_order_status_alter_warehousetransaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vi_address.ward'),
        ),
        migrations.AddField(
            model_name='user',
            name='ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vi_address.ward'),
        ),
    ]
