# Generated by Django 4.0.7 on 2022-10-18 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0068_supplier_ward_user_ward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricedetail',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='pricedetail',
            name='start_date',
        ),
    ]
