# Generated by Django 4.0.7 on 2022-10-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0070_inventoryreceivingvoucherdetail_quantity_base_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitexchange',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Hoạt động'),
        ),
    ]
