# Generated by Django 4.0.7 on 2022-11-03 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0071_unitexchange_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('exp', models.DateTimeField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.customer')),
            ],
        ),
    ]
