# Generated by Django 4.0.7 on 2022-11-07 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0072_otpcustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrefund',
            name='total',
            field=models.FloatField(default=0, verbose_name='Tổng tiền'),
        ),
    ]
