# Generated by Django 4.0.7 on 2022-11-07 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0073_orderrefund_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrefunddetail',
            name='order_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='management.orderdetail'),
        ),
    ]
