# Generated by Django 4.0.7 on 2022-11-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0074_orderrefunddetail_order_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrefunddetail',
            name='total',
            field=models.FloatField(default=0, verbose_name='Thành tiền'),
        ),
    ]
