# Generated by Django 4.0.7 on 2022-11-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0076_orderrefunddetail_quantity_base_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitexchange',
            name='is_report',
            field=models.BooleanField(default=False, verbose_name='Đơn vị dùng để báo cáo'),
        ),
    ]
