# Generated by Django 4.0.7 on 2022-11-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0078_alter_product_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroup',
            name='product_group_code',
            field=models.CharField(max_length=15, unique=True, verbose_name='Mã nhóm sản phẩm'),
        ),
    ]
