# Generated by Django 4.0.7 on 2022-11-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0081_remove_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryvoucherdetail',
            name='quantity_before',
            field=models.IntegerField(null=True, verbose_name='Số lượng trước'),
        ),
    ]
